# Generated by Django 4.0.4 on 2022-08-11 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_brand_product_sizes'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='status',
            field=models.CharField(choices=[('new', 'New'), ('top', 'Top')], default='new', max_length=20),
        ),
    ]
