# Generated by Django 4.0.4 on 2022-08-11 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_product_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='brand',
            field=models.CharField(choices=[('nike', 'Nike'), ('adiddas', 'Adiddas'), ('new balance', 'Newbalance')], default='nike', max_length=20),
        ),
        migrations.DeleteModel(
            name='Brand',
        ),
    ]
