# Generated by Django 4.0.4 on 2022-08-15 16:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0011_order_orderitem'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='date_orderes',
            new_name='date_ordered',
        ),
    ]
