# Generated by Django 4.0.4 on 2022-08-19 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0013_order_delivery_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('paypal', 'Paypal'), ('mpesa', 'Mpesa'), ('none', 'None')], default='none', max_length=20),
        ),
    ]
